version: "3.8"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - common-net
    environment:
      MYSQL_DATABASE: nearby
      MYSQL_ROOT_PASSWORD: "root"
  golang:
    # Create image with bazel with: `bazel run  //golang/cmd/nearby:nearby_image -- --norun`
    image: bazel/golang/cmd/nearby:nearby_image
    ports:
      - "8080:8080"
    networks:
      - common-net
    environment:
      SQL_DNS: "root:root@tcp(db:3306)/nearby"
volumes:
  data:
    driver: local
networks:
  common-net: {}